version: "3.9"

services:
  activation_base:
    build: .
    image: kimiahr/learningbase_athletes_performance_prediction
    volumes:
      - ai_system:/tmp
    command:
      - sh
      - "-c"
      - |
        rm -rf /tmp/learningBase && cp -r /learningBase /tmp/
    stdin_open: true
    tty: true

volumes:
  ai_system:
    external: true
