version: "3.9"

services:
  learning_base:
    build: .
    image: kimiahr/learningbase_athletes_performance_prediction
    volumes:
       - ai_system:/tmp
    command: sh  # simple shell, no rm/cp hack

volumes:
  ai_system:
    external: true
