version: "3.9"

services:
  activation_base:
    build: .
    image: kimiahr/activationbase_athletes_performance_prediction
    volumes:
      - ai_system:/tmp
    command: sh

volumes:
  ai_system:
    external: true
